AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:
  STV:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-STV'
      CodeUri: src/
      Handler: othertest.proc
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Layers:
        - arn:aws:lambda:eu-central-1:543143946998:layer:Dependencioes:1
      Events:
        AnalysePlaylistWID:
          Type: Api
          Properties:
            Path: /analyse/{id}
            Method: get
        AnalysePlaylistNID:
          Type: Api
          Properties:
            Path: /analyse
            Method: get
        PostAnalysePlaylistWID:
          Type: Api
          Properties:
            Path: /analyse/{id}
            Method: post
        PostAnalysePlaylistNID:
          Type: Api
          Properties:
            Path: /analyse
            Method: post
        Test:
          Type: Api
          Properties:
            Path: /
            Method: get
  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'